---
output: github_document
header-includes:
   - \usepackage{amsmath}
   - \usepackage{amssymb}
editor_options: 
  chunk_output_type: console
---

<!-- NEWS.md is generated from NEWS.Rmd. Please edit that file -->

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## tabula `r utils::packageVersion("tabula")` (`r Sys.Date()`)
<!-- TODO: refine, plotDate, plotTime, test -->

### New classes and methods
* `Matrix` this S4 class is now the superclass of all matrix-like classes.
* `AbundanceMatrix` this virtual S4 class is defined as the superclass of `CountMatrix`, `FrequencyMatrix` and `IncidenceMatrix`.
* `SpaceTime` this S4 class represents space-time informations.
* `plotDate()` gained a method for `AbundanceMatrix` objects.
* The functions `getDates()`, `setDates<-`, `getCoordinates()` and `setCoordinates<-` allow to extract and replace chronological and spatial informations in `AbundanceMatrix` objects.
* The functions `plotBertin()` and `plotFord()` replace `plotBar()`.

### Bugfixes & changes
* `CountMatrix`, `FrequencyMatrix` and `IncidenceMatrix` now also contain the `SpaceTime` class.
* The `plotDate()` method for `DateModel` objects now allows to display an activity or tempo plot.
* Deprecate `plotBar()`.

### Internals
* Reduce required R version to 3.2.
* Error handling has been revised and error messages have been harmonized.
* When a `Matrix` object is first created, an identifier (UUID v4) is generated with `generateUUID()`. This ID is preserved when coercing to another class. This makes it possible to identify objects representing the same initial data and associate them with the results of specific computations.
* Refer to {ggplot2} functions using `::` (stop importing the entire package).
* Replace `FactoMinerR::CA()` with `ca::ca()` (this avoids having to install all {FactoMineR} dependencies when only one function is used).
* Use `vapply()` instead of `sapply()`.
* Use `seq_len()` instead of `1:...`.

## tabula v1.2.0 (release date: 2019-03-20)
### New classes and methods
* The function `dateEvent()` allows to compute chronological models as described in Belanger and Husi (2006).
* `DateModel` this S4 class stores the results of `dateEvent()`.
* `SimilarityMatrix` this S4 class represents a (dis)similarity matrix.
* `plotDate()` method for `DateModel` objects.
* `plotSpot()` methods for `SimilarityMatrix` and `OccurrenceMatrix` objects.
* `[` operators for several classes.

### Bugfixes & changes
* `OccurrenceMatrix` now stores the number of times each pair of taxa occurs together in at least one sample.
* `similarity()` now returns an object of class `SimilarityMatrix`.
* `plotBar()` no longer add confidence interval by default.
* Remove useless accessors.

### Enhancements
* The function `similarity()` gained a new estimator: binomial co-occurrence assessment method (similarity between types).
* The function `seriate()` gained a new argument to pass a `BootCA` object.

### Internals
* Add an optional progress bars with {pbapply} in long running functions.

## tabula v1.1.0 (release date: 2018-12-30)
### Bugfixes & changes
* `similarity()` now returns a symmetric matrix.

### Enhancements
* The function `richness()` gained new estimators:
  * For abundance data: Chao1, bias-corrected Chao1, improved Chao1 and Abundance-based Coverage Estimator (ACE).
  * For replicated incidence data: Chao2, bias-corrected Chao2, improved Chao2 and Incidence-based Coverage Estimator (ICE).

### Internals
* Add references in the `Description` field of the DESCRIPTION file.
* Split the documentation for alpha-diversity measures.
* Split the documentation for beta-diversity measures.

## tabula v1.0.0 (release date: 2018-12-03)

* Initial version on CRAN

### New classes and methods
* `BootCA` this S4 class stores partial bootstrap CA-based seriation results.
* `[[` operators acting on `PermutationOrder` and `BootCA` to extract parts.

### Bugfixes & changes
* `refine()` method for `CountMatrix` now use `stats::rmultinorm()` for partial bootstrap CA.

### Enhancements
* Add the Zuni and Mississippi ceramics datasets.
* The function `similarity()` gained a new estimator: the Brainerd-Robinson coefficient of similarity.

### Internals
* Add a vignette for matrix seriation.

## tabula v0.9.0 (release date: 2018-11-16)

* First release.
