# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
on:
  release:
    types: [published]

name: drat

jobs:
  drat:
    uses: tesselle/packages/.github/workflows/drat.yaml@main
    with:
      REPO: ${{ github.event.repository.name }}
      RELEASE: ${{ github.event.release.tag_name }}
    secrets:
      TOKEN: ${{ secrets.ACCESS_TOKEN }}
