# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
on:
  push:
    branches: [main, master]
    tags: ['*']

name: pkgdown

jobs:
  pkgdown:
    uses: tesselle/packages/.github/workflows/pkgdown.yaml@main
    with:
      REPO: ${{ github.event.repository.name }}
      COMMIT: ${{ github.sha }}
    secrets:
      TOKEN: ${{ secrets.ACCESS_TOKEN }}
